### PR TITLE
feat: kosko4

### PR DESCRIPTION
**Pull request by revolunet**
lgtm

### CODE REVIEW

**Review by douglasduteil — APPROVED** [review]
@revolunet what do you think about using "standard" .gitlab-ci.env variables ?
Faking the env to be the commit of a release on master (dev test), with a tag (preprod test) and in production (prod test)
Similar to https://github.com/SocialGouv/sample-next-app/blob/master/.k8s/environments/.gitlab-ci.env

**Comment by revolunet** [comment]
> @revolunet what do you think about using "standard" .gitlab-ci.env variables ?
> Faking the env to be the commit of a release on master (dev test), with a tag (preprod test) and in production (prod test)
> Similar to https://github.com/SocialGouv/sample-next-app/blob/master/.k8s/environments/.gitlab-ci.env

I dont get why these default gitlab vars are not generated by us 🤔

**Comment by douglasduteil** [comment]
@revolunet because we didn't code it has default :)
Let's do this

**Comment by revolunet** [comment]
woot. it doesnt work bu you may find some related stuff here https://github.com/SocialGouv/kosko-charts/pull/322/files#diff-49c6f2d9654ca37688ae89ac5bba6e3ee6bb3656c87e748f2b43177c05179ebf

**Comment by revolunet** [comment]
i meant generated by us at runtime so we dont need to have the .env in the repos

**Comment by douglasduteil** [comment]
\ping @revolunet https://github.com/SocialGouv/kosko-charts/pull/323

**Comment by douglasduteil** [comment]
> woot. it doesnt work bu you may find some related stuff here [SocialGouv/kosko-charts#322 (files)](https://github.com/SocialGouv/kosko-charts/pull/322/files#diff-49c6f2d9654ca37688ae89ac5bba6e3ee6bb3656c87e748f2b43177c05179ebf)

U're faster than me 🏎️

**Pull request merged**
